spring:
  rabbitmq.host: 192.168.99.100
  jpa.hibernate.ddl-auto: none
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/test?autoReconnect=true&useSSL=false
    username: root
    password: root