spring:
  rabbitmq.addresses: ${vcap.services.github-rabbitmq.credentials.uri}
  jpa.hibernate.ddl-auto: none
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100/github?autoReconnect=true&useSSL=false
    username: root
    password: test