spring:
  application.name: github-analytics

  cloud.stream.bindings.input:
    destination: messages
    group: github-analytics

  jpa:
    database: MYSQL

server.port: ${PORT:8081}
endpoints.sensitive: false
management.security.enabled: false
